<#
.SYNOPSIS
  Phase 0 recon (and optional Phase 1 decompile) of a local Core Keeper install.
  Run on the PC where Core Keeper is installed, from the repo root:

    powershell -ExecutionPolicy Bypass -File tools\local-recon.ps1               # recon only
    powershell -ExecutionPolicy Bypass -File tools\local-recon.ps1 -Decompile    # + ilspycmd export

  Installs nothing. -Decompile requires ilspycmd to already be installed
  (dotnet tool install -g ilspycmd). Output: research\recon-local.md, decomp\<assembly>\ (gitignored).
#>
param(
  [string]$GamePath,
  [switch]$Decompile
)
$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot

function Find-CoreKeeper {
  $roots = @()
  try { $roots += (Get-ItemProperty 'HKCU:\Software\Valve\Steam' -ErrorAction Stop).SteamPath } catch {}
  $roots += "${env:ProgramFiles(x86)}\Steam", "$env:ProgramFiles\Steam"
  foreach ($r in ($roots | Where-Object { $_ } | Select-Object -Unique)) {
    $vdf = Join-Path $r 'steamapps\libraryfolders.vdf'
    $libs = @($r)
    if (Test-Path $vdf) {
      $libs += Select-String -Path $vdf -Pattern '"path"\s+"([^"]+)"' -AllMatches |
        ForEach-Object { $_.Matches } | ForEach-Object { $_.Groups[1].Value -replace '\\\\', '\' }
    }
    foreach ($l in $libs) {
      $p = Join-Path $l 'steamapps\common\Core Keeper'
      if (Test-Path $p) { return $p }
    }
  }
  foreach ($d in 'A','B','C','D','E','F','G') {
    $p = "${d}:\SteamLibrary\steamapps\common\Core Keeper"
    if (Test-Path $p) { return $p }
  }
  return $null
}

if (-not $GamePath) { $GamePath = Find-CoreKeeper }
if (-not $GamePath -or -not (Test-Path $GamePath)) { throw "Core Keeper not found. Pass -GamePath 'X:\...\Core Keeper'." }

$data = Get-ChildItem $GamePath -Directory -Filter '*_Data' | Select-Object -First 1
$managed = Join-Path $data.FullName 'Managed'
$il2cpp = Test-Path (Join-Path $GamePath 'GameAssembly.dll')
$backend = if ($il2cpp) { 'IL2CPP (STOP: switch to Cpp2IL/Il2CppDumper)' } elseif (Test-Path $managed) { 'Mono' } else { 'Unknown' }

$unityVer = (Get-Item (Join-Path $GamePath 'UnityPlayer.dll') -ErrorAction SilentlyContinue).VersionInfo.ProductVersion
$burst = Get-ChildItem $data.FullName -Recurse -Filter 'lib_burst_generated.dll' -ErrorAction SilentlyContinue | Select-Object -First 1

$all = Get-ChildItem $managed -Filter '*.dll'
$isEngine = '^(System|Mono|mscorlib|netstandard|Microsoft|UnityEngine|Unity\.|Newtonsoft|0Harmony|MonoMod|modio|Facepunch|Rewired|I2|QFSW|Sentry|io\.sentry)'
$game = $all | Where-Object { $_.Name -notmatch $isEngine } | Sort-Object Length -Descending
$unityPkgs = $all | Where-Object { $_.Name -match '^Unity\.' } | ForEach-Object { $_.BaseName } |
  ForEach-Object { ($_ -split '\.')[0..1] -join '.' } | Sort-Object -Unique

$md = @()
$md += '# Phase 0: Local recon (generated by tools/local-recon.ps1)'
$md += ''
$md += "- Install: ``$GamePath``"
$md += "- Unity version (UnityPlayer.dll): **$unityVer**"
$md += "- Scripting backend: **$backend**"
$md += "- Burst native library: $(if ($burst) { "present, $([math]::Round($burst.Length/1MB,1)) MB" } else { 'not found' })"
$md += ''
$md += '## Game-specific assemblies'
$md += ''
$md += '| Assembly | Size |'
$md += '|---|---|'
$game | ForEach-Object { $md += "| $($_.Name) | $([math]::Round($_.Length/1KB,1)) KB |" }
$md += ''
$md += '## Unity package assemblies present'
$md += ''
$md += ($unityPkgs | ForEach-Object { "``$_``" }) -join ', '
New-Item -ItemType Directory -Force (Join-Path $repo 'research') | Out-Null
$md -join "`n" | Set-Content -Encoding UTF8 (Join-Path $repo 'research\recon-local.md')
Write-Host "Wrote research\recon-local.md ($($game.Count) game assemblies, backend: $backend)"

if ($Decompile) {
  if ($il2cpp) { throw 'IL2CPP build: ilspycmd does not apply.' }
  if (-not (Get-Command ilspycmd -ErrorAction SilentlyContinue)) {
    throw 'ilspycmd not installed. Install it yourself with: dotnet tool install -g ilspycmd'
  }
  $targets = $game | Where-Object { $_.Name -match '^(Pug|Assembly-CSharp)' }
  foreach ($dll in $targets) {
    $out = Join-Path $repo "decomp\$($dll.BaseName)"
    New-Item -ItemType Directory -Force $out | Out-Null
    Write-Host "Decompiling $($dll.Name) -> decomp\$($dll.BaseName)"
    & ilspycmd -p -o $out -r $managed $dll.FullName
  }
  Write-Host 'Done. decomp\ is gitignored; do not commit or share it.'
}
